# main configuration file for serverless framework
# https://serverless.com/framework/docs/providers/openwhisk/guide/functions/

service: cb

provider:
  name: openwhisk
  memorySize: 256 # optional, default is 256
  timeout: 5 # optional, default is 60

functions:
    chaotic:
      handler: chaotic.handler

# run npm install to download the provider plugin
plugins:
    - serverless-openwhisk
